version: '3.1'

services:
  db:
    image: mysql
    container_name: mysqllab08
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - ./propuesto_1.sql:/docker-entrypoint-initdb.d/propuesto_1.sql